config/routes.rb
Rails.application.routes.draw do

  root to: "products#index"

  get '/sign_up' => 'users#new'
  post '/users' => 'users#create'

  get '/sign_in' => 'sessions#new'
  post '/sign_in' => 'sessions#create'
  get 'sign_out' => 'sessions#destroy'

  resources :products
  resources :order_items
  resource :cart, only: [:show]

  get 'finalize' => 'carts#finalize'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :user, optional: true

  before_save :calculate_total

  def calculate_total
    self.total_price = order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  def finalize(user)
    self.user_id = user.id
    self.status = 2
    self.save
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
  validates :name, :presence => true
  validates :description, :presence => true
  validates :price, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :orders

  def previous_orders
    self.orders.where(status: 2).includes(order_items: :product)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :admin
  helper_method :current_order

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def admin
    current_user && current_user.admin
  end

  def current_order
    session[:order_id] ? Order.find(session[:order_id]) : Order.new
  end

  def authorize
    redirect_to '/sign_in' unless admin
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    if current_user
      @previous_orders = current_user.previous_orders
    end
    @order_items = current_order.order_items
  end

  def finalize
    if current_user
      current_order.finalize(current_user)
      session[:order_id] = nil
      redirect_to cart_path
    else
      flash[:alert] = "You need to sign up or sign in to complete your order."
      redirect_to sign_in_path
    end
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @order = current_order
    @item = @order.order_items.new(item_params)
    @order.save
    session[:order_id] = @order.id
    @cart_tally =  current_order.order_items.length
    respond_to do |format|
      format.html { redirect_to products_path }
      format.js
    end
  end

  def update
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.update_attributes(item_params)
    @order.save
  end

  def destroy
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item_id = @item.id
    @item.destroy
    @order.save
    respond_to do |format|
      format.html { redirect_to cart_path }
      format.js
    end
  end

  private

  def item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authorize, except: [:index, :show]

  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def new
    @product = Product.new
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "You've successfully deleted a product!"
    redirect_to '/'
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "You've successfully created a new product. Kudos!"
      redirect_to '/'
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    if @product.save
      flash[:notice] = "You've successfully updated an existing product. Kudos!"
      redirect_to '/'
    else
      render :edit
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You've successfully signed in. Welcome!"
      redirect_to '/'
    else
      redirect_to '/sign_in'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've successfully signed out. Goodbye!"
    redirect_to '/sign_in'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:notice] = "You've successfully signed up. Welcome!"
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
  def cart_items
    current_order.order_items.length
  end
end

app/views/carts/show.html.erb
<h1>Shopping Cart</h1>

<% if @order_items.any? %>
  <% @order_items.each do |item| %>
    <div id="order_<%=item.id%>">
      <p><%= item.product.name %> | <%= link_to "Delete", order_item_path(item), remote: true, :data => {:confirm => "You sure?", :method => "delete"} %></p>
      <p> Unit Price: <%= number_to_currency item.product.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.product.price * item.quantity) %></p>
    </div>
  <% end %>
  <p id="order_total">Your Total: <%= number_to_currency current_order.total_price %></p>
  <p><%= link_to "Finalize order", finalize_path %></p>
<% else %>
  <p>Your shopping cart is empty.</p>
<% end %>

<% if @previous_orders %>
  <h3>Your order history:</h3>
  <% @previous_orders.each do |order| %>
    <h4>Order id: <%= order.id %> was completed on: <%= order.updated_at.strftime("%c") %></h4>
    <% order.order_items.each do |item| %>
      <p>Item name: <%= item.product.name %> | Quantity: <%= item.quantity %> | Price: <%= number_to_currency item.product.price %>
    <% end %>
    <p>Total cost: <%= number_to_currency order.total_price %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Week3CodeReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav>
    <div class="nav-wrapper">
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><span id="cartItems"><%= link_to "Cart | Total items: #{ cart_items }", cart_path %></span></li>
        <li><%= link_to "See all products", products_path %></li>
        <% if current_user %>
          <li><%= current_user.email %></li>
          <li><%= link_to "Sign out", '/sign_out' %></li>
        <% else %>
          <li><%= link_to "Sign up", 'sign_up' %></li>
          <li><%= link_to "Sign in", '/sign_in' %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/order_items/create.js.erb
$('#cartItems').html('<a href="/cart">Cart | Total items: ' + <%=  @cart_tally %> + '</a>');

app/views/order_items/destroy.js.erb
$('#order_total').html('Your Total: <%= number_to_currency current_order.total_price %>');
$('#order_' + <%= @item.id%>).hide();

app/views/products/edit.html.erb
<h1>Add a product.</h1>

  <%= form_for @product do |f| %>
    Name: <%= f.text_field :name %>
    Description: <%= f.text_field :description %>
    Price: <%= f.number_field :price, min: 0, step: 0.01 %>
  <%= f.submit "Submit" %>

<% end %>
<br><br>
<%= link_to "Delete Product", product_path(@product), :data => {:confirm => "You sure?", :method => "delete"} %>

app/views/products/index.html.erb
<h3>Products</h3>

<div class="row">
  <div class="section">
  <% @products.each do |product| %>
    <div class="col s4">
      <h4><%= product.name %></h4>
      <div id="product_no_details_<%=product.id%>">
        <%= link_to "Show Detail", product_path(product), remote: true %>
      </div>
      <div class="product_detail" id="product_details_<%=product.id%>">
        <%= link_to "Hide Detail", product_path(product), remote: true %>
        <div class="image_width">
          <%= image_tag "http://www.riobeauty.co.uk/images/product_image_not_found.gif"%>
        </div>
        <p><%= product.description %></p>
        <p><%= number_to_currency product.price %></p>
      </div>
      <%= form_for @order_item, remote: true do |f| %>
        <%= f.hidden_field :product_id, value: product.id %>
        <%= f.number_field :quantity, :min => 1, placeholder: "Oops, breaks if you don't add input!" %>
        <span class="waves-effect waves-light btn"><%= f.submit "Add to cart" %></span>
      <% end %>
    </div>
  <% end %>
</div>
</div>

app/views/products/new.html.erb
<h1>Add a product.</h1>

  <%= form_for @product do |f| %>
    Name: <%= f.text_field :name %>
    Description: <%= f.text_field :description %>
    Price: <%= f.number_field :price, min: 0, step: 0.01 %>
  <%= f.submit "Submit" %>

<% end %>

app/views/products/show.js.erb
$('#product_details_' + <%= @product.id%>).toggle();
$('#product_no_details_' + <%= @product.id%>).toggle();

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <span class="waves-effect waves-light btn"><%= f.submit "Sign up" %></span>
<% end %>